[product_info]
product_name = "MSIBuilder-Test"
product_version = "1.2.3"
manufacturer = "GrimOutlook"
product_language = 1033
product_code = "*"

[summary_info]
page_count = 200
revision_number = "*"
template = "x64;1033"
author = "Dominic Grimaldi"

[default_files]
program_files = "pg_files/"
program_files_32 = "pg_files_32/"
vital = [
    "pg_files/TestFile.txt",
]